apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/JaykumarAnbu/managed-argocd-lab2' # Update to match your fork.
    path: guestbook
    targetRevision: HEAD
  destination:
    namespace: guestbook
    name: staging2 # Update this value.
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
